#!/bin/bash
set -e  # Exit on error

# environment variables from Docker Cloud build-server
DOCKER_REPO="${DOCKER_REPO}"    # e.g. "index.docker.io/cryptopath/alpine"
DOCKER_TAG="${DOCKER_TAG}"      # e.g. "0.3.8-3" or "master"

# get base version (3.8-3 -> 3.8)
BASEVERSION="${DOCKER_TAG%%-*}"

# tag image with base-version
docker tag ${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REPO}:${BASEVERSION}

# tag image with 'latest'
docker tag ${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REPO}:latest

# don't push image if '--no-push' was specified
if [ "$1" != "--no-push" ]; then
  docker push ${DOCKER_REPO}:${BASEVERSION}
  docker push ${DOCKER_REPO}:latest
fi
